print('a')
print('Hello world')
a = int(input('vvedite chislo'))
b = int(input('vvedite chislo'))
print(a+b)
b = int(input('vvedite chislo'))
print(a-b)
print(a*b)
b = int(input('vvedite chislo'))
print('ghjwdvfuyvsduyfbv')
print(999)
print(888)